apiVersion: v1
kind: {{ .Values.kind}}
metadata:
  name: {{ .Values.backend.name }}
spec:
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - protocol: {{ .Values.protocol }}
      port: {{ .Values.backend.containerPort }}

---
apiVersion: {{ .Values.apiVersion }}
kind: {{ .Release.kind }}
metadata:
  name: {{ .Values.backend.name }}
  labels:
    env: {{ .Values.backend.env}}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      containers:
        - name: {{ .Values.backend.name }}
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          volumeMounts:
            - mountPath: /app
              name: backend-volume
      volumes:
        - name: backend-volume
          hostPath:
            path: /app

